#!/usr/bin/env bash

function __kob_help {

	__kobman_echo_no_colour "KOBman Manual"
	__kobman_echo_no_colour "-----------------------------"
	__kobman_echo_no_colour " $ kob <command> <qualifier> <environment> <namespace>"   
	__kobman_echo_no_colour ""
	__kobman_echo_no_colour "namespace"
	__kobman_echo_no_colour "-----------------------------"
	__kobman_echo_no_colour ""
	__kobman_echo_no_colour "A Namespace is a mechanism to partition resources created by users into a logically named group."
	__kobman_echo_no_colour "bcgov  : The namespace of the British Columbia"
	__kobman_echo_no_colour "hyperledgerkochi   : The namespace of Kochi"
	__kobman_echo_no_colour ""
	__kobman_echo_no_colour "environment"
	__kobman_echo_no_colour "-----------------------------"
	__kobman_echo_no_colour ""
	__kobman_echo_no_colour "tobvon     : The von network "
	__kobman_echo_no_colour "tob        : The org book"
	__kobman_echo_no_colour "greenlight : The greenlight"
	__kobman_echo_no_colour "kobman     : kobman environment"
	__kobman_echo_no_colour ""
	__kobman_echo_no_colour "qualifier"
	__kobman_echo_no_colour "-----------------------------"
	__kobman_echo_no_colour ""
	__kobman_echo_no_colour "--dev - Used to develop the specified environment. This can be used to make edits in the environment scripts."
	__kobman_echo_no_colour "--deploy - To run/deploy the specified environment"
	__kobman_echo_no_colour ""
	__kobman_echo_no_colour "command"
	__kobman_echo_no_colour "-----------------------------"
	__kobman_echo_no_colour "install     : $ kob install <qualifier> <environment> <namespace>"          
	__kobman_echo_no_colour "              The command is used to install the specified environment."
	__kobman_echo_no_colour "              Eg: $ kob install --dev tobvon bcgov"
	__kobman_echo_no_colour ""
	__kobman_echo_no_colour "uninstall   : $ kob uninstall <qualifier> <environment> <namespace>"
	__kobman_echo_no_colour "              The command is used to uninstall the specified environment."
	__kobman_echo_no_colour "              Eg: $ kob uninstall --dev tobvon bcgov"
	__kobman_echo_no_colour ""
	__kobman_echo_no_colour "status      : $ kob status"  
	__kobman_echo_no_colour "              The command displays the installed environments."
	__kobman_echo_no_colour ""
	__kobman_echo_no_colour "list        : $ kob list"
	__kobman_echo_no_colour "              The command lists the various environment that can be installed."
	__kobman_echo_no_colour ""
	__kobman_echo_no_colour "version     : $ kob version <environment>"
	__kobman_echo_no_colour "              The command displays the version of the specified environment."
	__kobman_echo_no_colour "              Eg: $ kob version tobvon"
	__kobman_echo_no_colour ""
	__kobman_echo_no_colour "help        : $ kob help"
    __kobman_echo_no_colour "              Displays the KOBman manual"
	
}
